"""add booking && rooms && users2 

Revision ID: 22dbfb33b16d
Revises: fcde8fbb314f
Create Date: 2023-09-19 14:46:27.866365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dbfb33b16d'
down_revision: Union[str, None] = 'fcde8fbb314f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
