version: "3.10"
services:
  data_base:
    image: postgres:16
    container_name: booking_db
    env_file:
      - .env-none-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-none-dev
    depends_on:
      - data_base
      - redis
    command: ["/hotels_fast_api/docker/app.sh"]
    ports:
      - 9000:8000

  celery:
    image: booking_celery
    build:
      context: . # celery это библиотека, у неё нет образа, берём из основного билда
    container_name: booking_celery
    # Если не работает эта команда, используйте закомментированную
    command: ["/hotels_fast_api/docker/celery.sh", "celery"] # Второй аргумен для if/elif в скрипте
    # command: sh -c "celery --app=app.tasks.celery:celery worker -l INFO"
    env_file:
      - .env-none-dev
    depends_on:
      - redis

  flower:
    image: booking_flower
    build:
      context: . # flower это библиотека, у неё нет образа, берём из основного билда
    container_name: booking_flower
    # Если не работает эта команда, используйте закомментированную
    command: ["/hotels_fast_api/docker/celery.sh", "flower"]
    # command: sh -c "celery --app=app.tasks.celery:celery flower"
    env_file:
      - .env-none-dev
    depends_on:
      - redis
    ports:
      - 5555:5555
