[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = Itrue
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line length = 88